### ISSUE TITLE
Returns None for ent._.kb_qid, ent._.url_wikidata, ent._.nerd_score

### ISSUE THREAD

**Issue by NDNW8K** [Lucaterre/spacyfishing#12]
Installation was succeseful. Using python 3.9

For the example provided in the demo:
```
import spacy

text_en = "Victor Hugo and Honoré de Balzac are French writers who lived in Paris."

nlp_model_en = spacy.load("en_core_web_sm")

nlp_model_en.add_pipe("entityfishing")

doc_en = nlp_model_en(text_en)

for ent in doc_en.ents:
        print((ent.text, ent.label_, ent._.kb_qid, ent._.url_wikidata, ent._.nerd_score))
```

getting the following results:

```
('Victor Hugo', 'PERSON', None, None, None)
('Honoré de Balzac', 'PERSON', None, None, None)
('French', 'NORP', None, None, None)
('Paris', 'GPE', None, None, None)
```

Can someone help with this, please?

**Comment by Lucaterre** [comment]
Hello @NDNW8K,

It seems that the default entity fishing endpoint (https://cloud.science-miner.com/nerd/) is down at the moment.

Indeed, this is a temporary solution but while waiting for the entity fishing service to come back and to test, change the default endpoint in `config` parameter as follow:

```python

nlp.add_pipe("entityfishing", config={
        "api_ef_base": "http://nerd.huma-num.fr/nerd/service"
    })
```

or for a more intensive use of spacyfishing you can install your own instance of entity-fishing: https://nerd.readthedocs.io/en/latest/build.html#

I hope this will help you

**Comment by NDNW8K** [comment]
Thanks a lot @Lucaterre! It helped

**Comment by itsDaiton** [comment]
I was getting no results using the default endpoint as well and this solution still works, as of 2024.
