### ISSUE TITLE
Update entity-fishing web demo link

### ISSUE THREAD

**Issue by kermitt2** [Lucaterre/spacyfishing#19]
Hi @Lucaterre !

Hope you're doing well :) 

Would it be possible to remove the link to http://nerd.huma-num.fr/nerd/ in the readme please? This server is 3-4 years old, so totally outdated version of entity-fishing, not maintained and not secured (and I have no clue who is managing it). 

The "official" web demo URL maintained and up-to-date is https://cloud.science-miner.com/nerd/

Many thanks!

**Comment by Lucaterre** [comment]
Hi @kermitt2,

I updated the EF client link in the documentation (external resources part)

thank you for this information 👍
